import type { Metadata } from "next";
import {Bricolage_Grotesque, DM_Sans} from "next/font/google";
import 'modern-normalize';
import "./globals.css";
import StoreProvider from "@/StoreProvider";

const geistBG = Bricolage_Grotesque({
  variable: "--font-title",
  weight: ["700"],
  subsets: ["latin"],
});

const geistDS = DM_Sans({
  variable: "--font-main",
  weight: ["300", "500", "600", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistBG.variable} ${geistDS.variable} antialiased`}>
        <StoreProvider>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
